name: Check Git Status on EC2

on:
  push:
    branches:
      - master
jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
    - name: Check Git Status on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/devops/game-of-life
          git status
