name: Check Git Status on EC2

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: Check Git Status on EC2
      env:
        DEVOPS_PASSWORD: ${{ secrets.DEVOPS_PASSWORD }}
      run: |
        sshpass -p "$DEVOPS_PASSWORD" ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} '
        sudo -S <<< "$DEVOPS_PASSWORD" su - devops << EOF
        cd /home/devops/game-of-life
        git status
        EOF
        '
      shell: bash
